module.exports = function (grunt) {

    /*
        Project Dependencies:
        ---------------------
            npm install grunt --save-dev
            npm install grunt-contrib-watch --save-dev
            npm install grunt-contrib-uglify --save-dev
            npm install grunt-contrib-requirejs --save-dev
            npm install grunt-contrib-sass --save-dev
    */

    grunt.initConfig({

        pkg: grunt.file.readJSON('package.json'),

        requirejs: {
            /* dynamically generated by custom task */
            /*
            compile: {
                options: {
                    baseUrl: './',
                    dir: './release/',
                    paths: {
                        jquery: 'libs/jquery'
                    },
                    fileExclusionRegExp: /^\.|node_modules|Gruntfile|\.md|package.json/,
                    optimize: 'none',
                    modules: [{
                        name: 'bootstrap-index'
                    },
                    {
                        name: 'bootstrap-about'
                    }]
                }
            }
            */
        }

    });

    // Load NPM Tasks
    grunt.loadNpmTasks('grunt-contrib-watch');
    grunt.loadNpmTasks('grunt-contrib-uglify');
    grunt.loadNpmTasks('grunt-contrib-requirejs');
    grunt.loadNpmTasks('grunt-contrib-sass');

    require('./grunt-customtasks.js')(grunt);

    grunt.registerTask('default', ['process']);
    
};